discord:
    token: ""
matrix:
    serverURL: 'http://10.8.0.1:8008'
    domain: ajann.xyz
mappings:
    -
        discordGuild: "267119038075895808"
        discordChannel: "270720288809811970"
        matrixRoom: ""
